import type { Metadata } from "next";
import PageHero from "@/components/sections/PageHero";
import CTA from "@/components/sections/CTA";
import Reveal from "@/components/ui/Reveal";
import { Container, SectionHeading } from "@/components/ui/Section";
import { ArrowRight, Check, Trail } from "@/components/ui/Icons";
import { sectors } from "@/lib/site";

export const metadata: Metadata = {
  title: "Sectors",
  description:
    "Trade and customs compliance is where the Aeronive platform went to work first. These are the regulated sectors it is architected for next, mapped to the regimes that govern each.",
};

const frameworkDetail = [
  {
    name: "EU AI Act",
    scope: "Risk classification & technical documentation",
    body: "Use cases are classified by risk tier during scoping. High-risk deployments get the logging, human-oversight, and technical documentation the tier requires, generated by the running system.",
  },
  {
    name: "ISO/IEC 42001",
    scope: "AI management system",
    body: "We structure the engagement so your AI management system has real artifacts behind it — defined roles, impact assessments, and a change-control record for every model and policy version.",
  },
  {
    name: "NIST AI RMF",
    scope: "Govern · Map · Measure · Manage",
    body: "Our four-phase engagement maps directly onto the RMF functions, so the assessment output slots into an existing risk programme rather than sitting beside it.",
  },
  {
    name: "SOC 2 Type II",
    scope: "Control evidence",
    body: "Access enforcement, change management, and monitoring all emit evidence continuously. Control testing draws from the same audit log the system writes in normal operation.",
  },
  {
    name: "HIPAA",
    scope: "PHI handling",
    body: "PHI never leaves the covered entity's environment. Minimum-necessary access is enforced at retrieval, and every disclosure path is logged against an identified actor.",
  },
  {
    name: "GDPR",
    scope: "Lawful basis & data subject rights",
    body: "Lineage makes erasure and access requests tractable: because every generated span traces to source records, we can answer what was processed and remove it at source.",
  },
];

const assurances = [
  {
    title: "Reconstructable decisions",
    body: "Every output resolves to the retrieval set, policy version, model version, and actor identity that produced it.",
  },
  {
    title: "Signed change control",
    body: "Model, prompt, and policy changes are versioned artifacts with signed approval — no silent updates to a production system.",
  },
  {
    title: "Human oversight paths",
    body: "Escalation to a qualified reviewer is a runtime control with a recorded outcome, not a documented intention.",
  },
  {
    title: "Independent evaluation",
    body: "Evaluation sets are owned by your subject-matter experts. We do not grade our own homework.",
  },
];

export default function SectorsPage() {
  return (
    <>
      <PageHero
        eyebrow="Sectors"
        title="Compliance is not a horizontal layer."
        lead="Each regulated sector carries its own regime, its own evidentiary standard, and its own definition of an unacceptable failure — which is why we shipped into one before claiming the rest. Trade and customs is where Aeronive EXIM runs today. The sectors below are direction, not a client list."
      />

      {/* ================= Sector detail ================= */}
      <section className="py-16 sm:py-24">
        <Container>
          <div className="flex flex-col">
            {sectors.map((s, i) => (
              <Reveal key={s.slug}>
                <article
                  id={s.slug}
                  className="scroll-mt-28 border-t border-line py-12 first:border-t-0 first:pt-0 lg:py-16"
                >
                  <div className="grid gap-10 lg:grid-cols-[0.95fr_1.05fr] lg:gap-16">
                    <div>
                      <div className="flex items-baseline gap-4">
                        <span className="font-mono text-[11px] tracking-[0.14em] text-ghost">
                          {String(i + 1).padStart(2, "0")}
                        </span>
                        <h2 className="text-[clamp(1.5rem,2.8vw,2.1rem)] leading-[1.1] font-medium text-gradient">
                          {s.name}
                        </h2>
                      </div>
                      <p className="mt-5 max-w-[52ch] text-[14px] leading-[1.75] text-body">
                        {s.summary}
                      </p>
                      <ul className="mt-7 flex flex-wrap gap-2">
                        {s.regimes.map((r) => (
                          <li
                            key={r}
                            className="rounded-lg border border-line-strong bg-veil px-2.5 py-1.5 font-mono text-[10px] tracking-[0.05em] text-muted"
                          >
                            {r}
                          </li>
                        ))}
                      </ul>
                    </div>

                    <div className="card p-6 sm:p-7">
                      <span className="label-mono">Representative use cases</span>
                      <ul className="mt-5 flex flex-col gap-4">
                        {s.useCases.map((u) => (
                          <li key={u} className="flex items-start gap-3">
                            <span className="mt-[7px] h-1 w-1 shrink-0 rounded-full bg-brand" />
                            <span className="text-[13.5px] leading-relaxed text-body">
                              {u}
                            </span>
                          </li>
                        ))}
                      </ul>
                    </div>
                  </div>
                </article>
              </Reveal>
            ))}
          </div>
        </Container>
      </section>

      {/* ================= Frameworks ================= */}
      <section id="frameworks" className="scroll-mt-28 py-24 sm:py-32">
        <Container>
          <SectionHeading
            eyebrow="Compliance posture"
            title="What each regime actually requires of the system."
            lead="Not a badge wall. These are the obligations we design the architecture around, and what the running system produces to satisfy them."
          />

          <div className="mt-16 grid gap-4 md:grid-cols-2 lg:grid-cols-3">
            {frameworkDetail.map((f, i) => (
              <Reveal key={f.name} delay={Math.min(i, 3) * 0.07}>
                <article className="card card-hover flex h-full flex-col p-6">
                  <div className="flex items-start justify-between gap-3">
                    <h3 className="text-[16px] font-medium tracking-[-0.02em] text-ink">
                      {f.name}
                    </h3>
                    <Trail className="h-4 w-4 shrink-0 text-ghost" />
                  </div>
                  <span className="mt-2 font-mono text-[10px] tracking-[0.06em] text-brand">
                    {f.scope}
                  </span>
                  <p className="mt-4 text-[13px] leading-relaxed text-muted">
                    {f.body}
                  </p>
                </article>
              </Reveal>
            ))}
          </div>

          <Reveal delay={0.1}>
            <p className="mt-10 text-center text-[12.5px] text-ghost">
              Operating under a regime not listed here?{" "}
              <a
                href="/contact"
                className="text-body underline decoration-white/20 underline-offset-4 transition-colors hover:text-brand-text"
              >
                Tell us which one
              </a>
              .
            </p>
          </Reveal>
        </Container>
      </section>

      {/* ================= Assurance ================= */}
      <section className="py-16 sm:py-24">
        <Container>
          <div className="card grain relative overflow-hidden p-8 sm:p-12">
            <div
              className="pointer-events-none absolute inset-0"
              style={{
                background:
                  "radial-gradient(ellipse 60% 70% at 15% 0%, var(--c-glow-soft), transparent 65%)",
              }}
            />
            <div className="relative grid gap-12 lg:grid-cols-[0.85fr_1.15fr] lg:gap-16">
              <div>
                <span className="label-mono">Assurance</span>
                <h2 className="mt-5 text-[clamp(1.7rem,3vw,2.3rem)] leading-[1.1] font-medium text-gradient">
                  Defensible under scrutiny, not just compliant on paper.
                </h2>
                <p className="mt-5 text-[13.5px] leading-relaxed text-muted">
                  The difference between a system that passes review and one that
                  survives an incident is whether it can explain itself
                  afterwards.
                </p>
              </div>

              <div className="grid gap-x-10 gap-y-8 sm:grid-cols-2">
                {assurances.map((a, i) => (
                  <Reveal key={a.title} delay={i * 0.07}>
                    <div>
                      <div className="flex items-center gap-2.5">
                        <Check className="h-3.5 w-3.5 shrink-0 text-ok" />
                        <h3 className="text-[14.5px] font-medium text-ink">
                          {a.title}
                        </h3>
                      </div>
                      <p className="mt-2.5 pl-[26px] text-[12.5px] leading-relaxed text-faint">
                        {a.body}
                      </p>
                    </div>
                  </Reveal>
                ))}
              </div>
            </div>
          </div>
        </Container>
      </section>

      {/* ================= Cross-link ================= */}
      <section className="pb-8">
        <Container>
          <Reveal>
            <a
              href="/solutions"
              className="card card-hover group flex items-center justify-between gap-6 p-7"
            >
              <div>
                <span className="label-mono">Next</span>
                <h3 className="mt-2 text-[18px] font-medium tracking-[-0.02em] text-ink">
                  How the system is actually built
                </h3>
              </div>
              <ArrowRight className="h-5 w-5 shrink-0 text-faint transition-all duration-400 group-hover:translate-x-1 group-hover:text-brand" />
            </a>
          </Reveal>
        </Container>
      </section>

      <CTA
        title="Scope it against your regime."
        lead="Tell us the sector and the frameworks you answer to. We will come back with a risk-tiered view of which use cases are viable and what each one requires."
        secondary={{ label: "Platform detail", href: "/solutions" }}
      />
    </>
  );
}
